
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;


public class QuizPG1 extends javax.swing.JFrame {
      String questions[][]=new String [10][5];
      String answers [][]=new String [10][1];
      String userans[][]=new String[10][1];
      public static int timer = 15;
      public static int answerGiven = 0;
      public static int count = 0;
      public static int score = 0;
      String name;
    public QuizPG1(String name) {
        this.name = name;
        initComponents();
        setSize(980,750);
        setLocation(500,150);
        
        questions[0][0]="What is the general purpose of JAVA VIRTUAL MACHINE(JVM)?";
        questions[0][1]="Compile Java Code";
        questions[0][2]="Execute Java Code";  //correct 
        questions[0][3]="Debug Java Code";
        questions[0][4]="Package Java Code";
        
        questions[1][0]="Which keyword is used to define constant variable in JAVA?";
        questions[1][1]="final";   //correct
        questions[1][2]="const";
        questions[1][3]="var";
        questions[1][4]="static";
        
        
        questions[2][0]="In JAVA which access modifier provides the widest visibility?";
        questions[2][1]="private";
        questions[2][2]="default";
        questions[2][3]="protected";
        questions[2][4]="public";  //correct
        
        questions[3][0]="Which is the correct syntax to create an object of a class named 'My Class'?";
        questions[3][1]="object MyClass = new object;";
        questions[3][2]="MyClass obj = create MyClass();";
        questions[3][3]="MyClass obj = new MyClass();";   //correct
        questions[3][4]="object obj = new MyClass;";
        
        questions[4][0]="Which data type is used to store a single Unicode character in JAVA?";
        questions[4][1]="char";  //correct
        questions[4][2]="string";
        questions[4][3]="character";
        questions[4][4]="unicode";
        
        questions[5][0]="Which statement is used to exit a loop in JAVA?";
        questions[5][1]="halt";
        questions[5][2]="stop";
        questions[5][3]="end";
        questions[5][4]="break";  //correct
        
        questions[6][0]="Which of the following is not a primitive data type in JAVA?";
        questions[6][1]="int";
        questions[6][2]="float";
        questions[6][3]="boolean";
        questions[6][4]="object";  //correct
        
        questions[7][0]="Which JAVA loop is guaranteed to execute at least once?";
        questions[7][1]="while";
        questions[7][2]="do-while";  //correct
        questions[7][3]="for";
        questions[7][4]="for-each";
        
        questions[8][0]="Which method is called automatically when an object is created from a class?";
        questions[8][1]="start()";
        questions[8][2]="initialize()";
        questions[8][3]="main()";
        questions[8][4]="constructor()";  //correct

        
        questions[9][0]="Which JAVA keyword is used to explicitly raise an exception?";
        questions[9][1]="raise";
        questions[9][2]="throw";   //correct
        questions[9][3]="exception";
        questions[9][4]="try";   
        
        answers[0][0]="Execute Java Code";
        answers[1][0]="final";
        answers[2][0]="public";
        answers[3][0]="MyClass obj = new MyClass();";
        answers[4][0]="char";
        answers[5][0]="break";
        answers[6][0]="object";
        answers[7][0]="do-while";
        answers[8][0]="constructor()";
        answers[9][0]="throw";
        
        buttonGroup1.add(opt1);
        buttonGroup1.add(opt2);
        buttonGroup1.add(opt3);
        buttonGroup1.add(opt4);
        submit.setEnabled(false);
        add(submit);
        start(count);
        setVisible(true);
        
    }

   /* QuizPG1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        qno = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 340));
        jPanel1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));
        jPanel1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));
        jPanel1.add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));
        jPanel1.add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));
        jPanel1.add(qno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        next.setBackground(new java.awt.Color(255, 204, 204));
        next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 515, 160, 50));

        submit.setBackground(new java.awt.Color(255, 204, 204));
        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
     //   DefaultTableModel tb = (DefaultTableModel) tablemodel1.getModel();
        repaint();    
        answerGiven = 1;
        if (buttonGroup1.getSelection()== null){
               userans[count][0]="";
           }else{
               userans[count][0]=buttonGroup1.getSelection().getActionCommand();
           }
        if(count == 8){
            next.setEnabled(false);
            submit.setEnabled(true);
        }
        count++;
        start(count);
    }//GEN-LAST:event_nextActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:  
        answerGiven = 1;
        if (buttonGroup1.getSelection()==null){
               userans[count][0]="";
           }else{
               userans[count][0]=buttonGroup1.getSelection().getActionCommand();
           }
             for(int i=0 ; i<userans.length;i++){
                 if(userans[i][0].equals(answers[i][1])){
                     score += 10;
                 }
             }
             setVisible(false);
             new Score(name,score);
             submit.setEnabled(true);
           //  SCOREtf.setText(score);
                 
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public void paint(Graphics g){
        super.paint(g);
        
        String time = "Time Left:"+ timer + "seconds";
        g.setColor(Color.RED);
        g.setFont(new Font("Tahoma",Font.BOLD,25));
        if (timer > 0){
           g.drawString(time, 600, 450);    
        }else{
            g.drawString("Times Up!!", 600, 450);   
        }
       timer--;
       
       try{
           Thread.sleep(1000);
           repaint();
       }  catch (InterruptedException ex) {
              Logger.getLogger(QuizPG1.class.getName()).log(Level.SEVERE, null, ex);
          }
       if (answerGiven == 1){
           answerGiven = 0;
           timer = 15;
       }else if (timer < 0) {
           
           if(count == 8){
            next.setEnabled(false);
            submit.setEnabled(true);
            
         } 
           if(count == 9){  //submit button
               if(count < userans.length){
             if (buttonGroup1.getSelection()==null){
               userans[count][0]="";
           }else{
               userans[count][0]=buttonGroup1.getSelection().getActionCommand();
           }
       }
              
             for(int i=0 ; i<userans.length;i++){
                 if(userans[i][0]!= null && userans[i][0].equals(answers[i][0])){
                     score += 10;
                 }
             }
             setVisible(false);
              new Score(name,score);
         } else{      // next button
           
           if (buttonGroup1.getSelection()==null){
               userans[count][0]="";
           }else{
               userans[count][0]=buttonGroup1.getSelection().getActionCommand();
           }
           count++;
           start(count); 
           }
       }
    
    }
   
    public void start(int count){
        qno.setText(""+ (count +1)+".");
        question.setText(questions[count][0]);
        opt1.setText(questions[count][1]);
        opt1.setActionCommand(questions[count][1]);
        
        opt2.setText(questions[count][2]);    
        opt2.setActionCommand(questions[count][2]);
        
        opt3.setText(questions[count][3]);        
        opt3.setActionCommand(questions[count][3]);
        
        opt4.setText(questions[count][4]);
        opt4.setActionCommand(questions[count][4]);
        
        buttonGroup1.clearSelection();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizPG1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizPG1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizPG1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizPG1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizPG1("user").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JLabel qno;
    private javax.swing.JLabel question;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
